### ISSUE TITLE
Only transfers to minnowbooster are counted towards the SPP

### ISSUE THREAD

**Issue by MWFIAE** [stoodkev/steemplus-api#10]
#### Expected behavior
SteemPlus Points (SPP) should be rewarded for various activities, such as promoting your post with minnowbooster or postpromoter. 

#### Actual behavior
Only transfers to minnowbooster are counted. This is caused by a wrong condition in the sql statement that the job uses to calculate the points.
Other activities to earn points like setting steemplus-pay as a beneficiary still works as expected. 

#### How to reproduce
- Send 1 SBD to postpromoter
- Wait 1 hour so that the job runs
- Check the API to see that your points weren't updated and the transfer wasn't included. 

#### Solution
The solution is very simple. 
In the SQL-Statement one has to replace the ```[from]``` with a ```[to]```.
Turning from this: 
![](https://cdn.steemitimages.com/DQmdu3DYqpd3jk74PuYkETpZFVbjBXtqUensEStBMT6VYVi/image.png)
To this: 
![](https://cdn.steemitimages.com/DQmNUf2UfyqWnN8cejbNBF3Gh4Uhx25BudW5uPwHr1RMBVr/image.png)

Another indicator that "to" is the right field to use is the fact that later the field is later used to determine the type of transaction. 
![](https://cdn.steemitimages.com/DQmQojcB2VgZWXS19YufYhu1N8LWZpPmqJQQMnDPCpUfkt1/image.png)

I would have made a Pull-Request for it, but after telling @cedricguillas (who is in charge for this function) what and where the problem is he immediately started working on it. (Making a PR and juggle with the issue would probably be just more overhead than quickly replacing the word himself. ) 

#### Recording Of The Bug
Before promoting my post with postpromoter:
[![](https://cdn.steemitimages.com/DQmbXqpVCukkEUFjU3KQCykt1NVyXrBJVHB7PGBAckEvmTN/image.png)](https://cdn.steemitimages.com/DQmbXqpVCukkEUFjU3KQCykt1NVyXrBJVHB7PGBAckEvmTN/image.png)
Promoting a post:
[![](https://cdn.steemitimages.com/DQmZtM9dtgsyKk2SgMC7BcA6Fzx4CGJs7cFkgz2bvahM7UU/image.png)](https://cdn.steemitimages.com/DQmZtM9dtgsyKk2SgMC7BcA6Fzx4CGJs7cFkgz2bvahM7UU/image.png)
After promoting my post with postpromoter:
[![](https://cdn.steemitimages.com/DQmbXqpVCukkEUFjU3KQCykt1NVyXrBJVHB7PGBAckEvmTN/image.png)](https://cdn.steemitimages.com/DQmbXqpVCukkEUFjU3KQCykt1NVyXrBJVHB7PGBAckEvmTN/image.png)
<sub>(click the picture to enlarge)</sub>
It is somewhat difficult to see , but my points weren't increased and only the transfer to minnowbooster which I had before was counted. 

Already told @cedricguillas about it, who already implemented a fix.

**Comment by stoodkev** [comment]
Thanks for reaching to @cedricguillas.
